//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudent", ReplyAction="http://tempuri.org/IService/GetStudentResponse")]
        SoapService.Student GetStudent(string searchParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudent", ReplyAction="http://tempuri.org/IService/GetStudentResponse")]
        System.Threading.Tasks.Task<SoapService.Student> GetStudentAsync(string searchParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudents", ReplyAction="http://tempuri.org/IService/GetStudentsResponse")]
        SoapService.Student[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStudents", ReplyAction="http://tempuri.org/IService/GetStudentsResponse")]
        System.Threading.Tasks.Task<SoapService.Student[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddUpdateStudent", ReplyAction="http://tempuri.org/IService/AddUpdateStudentResponse")]
        void AddUpdateStudent(SoapService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddUpdateStudent", ReplyAction="http://tempuri.org/IService/AddUpdateStudentResponse")]
        System.Threading.Tasks.Task AddUpdateStudentAsync(SoapService.Student student);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference.IService>, Client.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoapService.Student GetStudent(string searchParam) {
            return base.Channel.GetStudent(searchParam);
        }
        
        public System.Threading.Tasks.Task<SoapService.Student> GetStudentAsync(string searchParam) {
            return base.Channel.GetStudentAsync(searchParam);
        }
        
        public SoapService.Student[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<SoapService.Student[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public void AddUpdateStudent(SoapService.Student student) {
            base.Channel.AddUpdateStudent(student);
        }
        
        public System.Threading.Tasks.Task AddUpdateStudentAsync(SoapService.Student student) {
            return base.Channel.AddUpdateStudentAsync(student);
        }
    }
}
